services:
  server:
    build: ../part 5
    user: nginx
  proxy:
    build: .
    ports:
      - 80:8080
    healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 30s
            timeout: 10s
            retries: 5